### ISSUE TITLE
default lmdb storage size is too large, causing boot error

### ISSUE THREAD

**Issue by m3ngyang** [hyperledger-labs/trusted-compute-framework#19]
https://github.com/hyperledger-labs/trusted-compute-framework/blob/fead0d3f715a53cef1079cb271015b27d655bae9/tcs/core/common/packages/db_store/lmdb_store.cpp#L35-L40

The default lmdb storage size is too large, which may cause boot error. Can we set it as a booting config parameter ❓

**Comment by Ram-srini** [comment]
I guess we are using DEFAULT_DB_STORE_SIZE parameter to set the map size using mdb_env_set_mapsize(). It will set the map size to this 1TB, but allocate that much memory affront. As per the mdb API mdb_env_set_mapsize(), size should be a multiple of the OS page size. The default is 10485760 bytes. The size of the memory map is also the maximum size of the database. The value should be chosen as large as possible, to accommodate future growth of the database.

This size can be read from boot config parameter.

**Comment by danintel** [comment]
LMDB files are "sparse" files and do not use disk space until needed. So a 1TB sparse file does not use 1TB of disk storage.

To copy or backup these files, Linux commands have sparce file options, such as cp --sparse or tar -S

**Comment by m3ngyang** [comment]
closed by #45
